version: 2
# copied from the CircleCI demo hashicorp/learn-terraform-circleci

jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:0.13.5
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: hashicorp/terraform:0.13.5
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply:
          context:
            - Terraform State
            - Github Admin
      - hold-apply:
          context:
            - Terraform State
            - Github Admin
          type: approval
          requires:
            - plan-apply
          filters:
            branches:
              only: main
      - apply:
          context:
            - Terraform State
            - Github Admin
          requires:
            - hold-apply
          filters:
            branches:
              only: main
